#!/usr/bin/env Rscript

# Copy the Lua filter (web_and_slides.lua) into every module as
# web_and_slides_autogenerated.lua.
#
# Register this as `pre-render` in _quarto.yml to run it before every local render.
#
# Usage: Rscript sync_filter.r        (run from the repo root)

source_lua <- "web_and_slides.lua"
copy_name  <- "web_and_slides_autogenerated.lua"   # also referenced by web_and_slides.r

if (!file.exists(source_lua)) {
  stop("Cannot find ", source_lua, " in ", getwd(),
       " -- run this from the repo root")
}

banner <- c(
  paste0("-- ", copy_name, " -- AUTOGENERATED, DO NOT EDIT."),
  paste0("-- Copied from the repo root's ", source_lua, " by sync_filter.r (see _quarto.yml)."),
  "-- Edit that file instead; this copy exists so the module is self-contained.",
  "--"
)
content <- c(banner, readLines(source_lua, warn = FALSE))

# modules are the top-level directories holding an index.qmd
modules <- dirname(list.files(pattern = "^index\\.qmd$", recursive = TRUE))
modules <- setdiff(modules, ".")
if (length(modules) == 0) message("sync_filter: no modules found")

for (m in modules) {
  dest <- file.path(m, copy_name)
  if (file.exists(dest) && identical(readLines(dest, warn = FALSE), content)) next
  writeLines(content, dest)
  message("sync_filter: wrote ", dest)
}
